# Generated by Django 3.2.25 on 2025-03-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('dep_description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['dep_name'],
            },
        ),
    ]
