# Generated by Django 3.2.25 on 2025-03-14 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home123', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('timings', models.CharField(max_length=255)),
                ('availability', models.TextField(default='[]')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='home123.department')),
            ],
        ),
    ]
