# Generated by Django 3.2.25 on 2025-03-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home123', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_name', to='home123.doctor')),
                ('doc_spc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_spc', to='home123.doctor')),
            ],
        ),
    ]
