# Generated by Django 3.2.25 on 2025-03-15 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home123', '0003_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='doc_spc',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='timings',
        ),
        migrations.AlterField(
            model_name='book',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='home123.doctor'),
        ),
    ]
