# Generated by Django 3.2.25 on 2025-03-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home123', '0004_auto_20250316_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='doc_name',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
