# Generated by Django 3.2.25 on 2025-03-15 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home123', '0006_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the doctor', max_length=255)),
                ('specialization', models.CharField(help_text="Doctor's specialization (e.g., Cardiology, Neurology)", max_length=255)),
                ('image', models.ImageField(blank=True, help_text="Doctor's profile picture", null=True, upload_to='doctors/')),
                ('qualification', models.CharField(help_text='Educational qualifications (e.g., MBBS, MD)', max_length=255)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('timings', models.CharField(help_text='Available timings (e.g., 9 AM - 5 PM)', max_length=255)),
                ('availability', models.TextField(default='[]', help_text='JSON-formatted availability slots')),
                ('department', models.ForeignKey(help_text='Department to which the doctor belongs', on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='home123.department')),
            ],
        ),
    ]
