# Generated by Django 3.2.25 on 2025-03-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home123', '0007_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(help_text="Patient's full name", max_length=255)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5')),
                ('comment', models.TextField(help_text="Patient's feedback or testimonial")),
                ('submitted_on', models.DateTimeField(auto_now_add=True, help_text='Date of submission')),
            ],
        ),
    ]
