# Generated by Django 3.2.25 on 2025-03-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home123', '0010_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255, verbose_name='Patient Name')),
                ('p_phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('p_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('booked_on', models.DateField(auto_now=True, verbose_name='Booked On')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home123.doctor', verbose_name='Doctor Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
