# Generated by Django 3.2.25 on 2025-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home123', '0011_auto_20250316_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, verbose_name="Patient's Name")),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Feedback Message')),
                ('submitted_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted On')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Feedbackform',
        ),
    ]
