# Generated by Django 3.2.25 on 2025-03-16 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home123', '0012_auto_20250316_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255, verbose_name='Patient Name')),
                ('p_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='Rating')),
                ('comments', models.TextField(blank=True, verbose_name='Feedback Comments')),
                ('submitted_on', models.DateField(auto_now_add=True, verbose_name='Submitted On')),
                ('doc_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home123.doctor', verbose_name='Doctor Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
